### PR TITLE
This fixes rosjava/rosjava_core#237. Added fix to remove Publishers a…

### PR DESCRIPTION
**Pull request by stratomda**
…nd Subscribers from topicParticipantManager on node shutdown. Added fix to remove listeners from DefaultPublisher on shutdown.

### CODE REVIEW

**Review by jubeira — COMMENTED** [review]
LGTM.
It sounds a bit odd to me that there is no way of doing both `removeSubscriber` and `subscriber.shutdown()` in a single operation, but given the current class relationships I think it's not bad to proceed like this.
Another option would be to delegate the publisher / subscriber shutdown operation to the topicParticipantManager completely, and replace these loops for something like
```java
topicParticipantManager.shutdownAll()
```

**Comment by stratomda** [comment]
@jubeira I can investigate that if you want? I tested to see if I actually needed to remove the publishers and subscribers from the topicParticipantManager and it didn't seem like it was required. I just figured for completeness I would remove the publisher/subscriber once they shutdown. I do like the idea of having a single point of entry to shutdown everything in the topicParticipantManager.

**Comment by jubeira** [comment]
That would be great! So you are saying that just adding shutdown line solves the leak? It does make sense to remove the publisher/subscriber as you say though.

I checked the `DefaultSubscriber` and the listeners are shut down already, apparently someone missed the method call you just added for `DefaultPublisher`.
Thanks @stratomda !

**Comment by stratomda** [comment]
@jubeira Yeah adding the shutdown call to the DefaultPublisher solves the leak. I did check the DefaultSubscriber and noticed they correctly called shutdown. I'll add the enhancement to the topicParticipantManager to shutdown all subscribers and publishers along with remove them from the ListenerGroup collection.

**Comment by stratomda** [comment]
@jubeira What are your thoughts on this for the shutdown method in TopicParticipantManager? 
```java
public void shutdown()
  {
    publishers.forEach((k, publisher) -> {
      publisher.shutdown(); this.removePublisher(publisher);
    });
    publisherConnections.clear();
    subscribers.forEach((k, subscriber) -> {
      subscriber.shutdown(); this.removeSubscriber(subscriber);
    });
    subscriberConnections.clear();
  }
```

**Comment by jubeira** [comment]
One question and one observation:
- Now that you mention `subscriberConnections`, what about `publisherConnections`? Does that need to be cleaned too? Right now, none of them are being cleared...
- I personally like the lambdas feature, but the problem here is that this code may run on Android. I've never used them on Android; will this work for apps running in old Android versions? I read [this article](https://developer.android.com/guide/platform/j8-jack.html) and it's a bit unclear to me if this will work with ros-android without any modification to the Gradle scripts. 

If they may cause some problems on Android, I would go for the not-so-cool but well-known standard for loop. Otherwise, your `shutdown` proposal seems fine!

**Comment by stratomda** [comment]
I clean up the publisherConnections as well. I just tried to compile with the lambda feature and it complained. I will go with the not-so-cool approach :)

**Review by jubeira — APPROVED** [review]
I think it looks better this way!

**Comment by adamantivm** [comment]
Very nice guys, thank you

**Pull request merged**
