### PR TITLE
Gradle upgrade: 3.5.1

### PR DESCRIPTION
**Pull request by jubeira**
Upgrades Gradle version to 3.5.1.

### CODE REVIEW

**Comment by ernestmc** [comment]
@jubeira got this warning:
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_1vawmrqr5l4gyfttx42zcsqtv.run(/home/ecorbellini/repos/rosjava/src/rosjava_core/build.gradle:25)
```

**Comment by jubeira** [comment]
See https://github.com/rosjava/zeroconf_jmdns_suite/pull/53#issuecomment-383078705.

**Comment by jubeira** [comment]
I updated the `clean` task in docs as well; now the warning should not appear at all.

**Comment by ernestmc** [comment]
lgtm

**Pull request merged**
