### PR TITLE
Added a new node class to wrap a native ROS node.

### PR DESCRIPTION
**Pull request by ernestmc**
Added a new node class "NativeNodeMain" to wrap the loading and execution of a native library. It is focused on running a native code compiled ROS node from Rosjava.

### CODE REVIEW

**Comment by stonier** [comment]
LGTM.

**Comment by jabrena** [comment]
It is very nice development.
Any tutorial or example to test?

Juan Antonio

**Comment by ernestmc** [comment]
@jabrena you can find a tutorial using this node [here](http://wiki.ros.org/android_ndk/Tutorials/WrappingNativeRosjavaNode).

**Comment by jabrena** [comment]
hi @ernestmc, I read the link but the tutorial put the focus on Android. Does exist the possibility to use the idea in Java 8?

**Comment by ernestmc** [comment]
@jabrena yes, it should work fine to load any native library in Java. Please let me know if you are able to test it.

**Comment by jabrena** [comment]
Yes, this is the idea.
Take a look this project:
https://github.com/jabrena/ev3dev-lang-java

Cheers

**Comment by jabrena** [comment]
Hi @ernestmc tell me how to begin the process. I would like to participate in the process to test this way to use rosjava.

**Comment by ernestmc** [comment]
@jabrena sure! I'll be glad to help you! I would like to invite you to continue this conversation in the new rosjava [Discourse site](http://discourse.ros.org/c/rosjava). It could be useful for others too.

**Comment by jabrena** [comment]
Nice, tonight I will join to the discussion.
In the past, I was doing some nodes for a old ROS version:
http://wiki.ros.org/nxt_lejos

Cheers

**Pull request merged**
