### PR TITLE
Zeroconf package

### PR DESCRIPTION
**Pull request by KazutoMurase**
I made some classes for app_chooser application.
Especially I made a new package "java.org.ros.zeroconf" to make zeroconf function on android.

### CODE REVIEW

**Comment by chadrockey** [comment]
Looks like you don't have your git email address set up correctly.  Can you fix your commits so that your name shows up instead of 'pr2'?  While the pr2s are great, I don't think they can program rosjava yet.  :)

**Comment by chadrockey** [comment]
Would this be better in a new repo?  @damonkohler What do you think?  We could make a rosjava/zeroconf repo for this feature if it doesn't belong in the core functionality.

Also, thanks Kazuto for fixing your commit names!

**Comment by KazutoMurase** [comment]
Yeah, actually, zeroconf doesn't seem to belong in the core functionality for me. I try to make rosjava_zeroconf repo.

**Comment by KazutoMurase** [comment]
I created the new repo, "rosjava_zeroconf" in OSRF (https://bitbucket.org/osrf/rosjava_zeroconf) . So, there is no need to change this repo. I want to cancel the pull request.
I have no right to reject. Would you reject it?

**Comment by stonier** [comment]
Should be able to 'close' it kazuto.

**Pull request closed without merging**
