### PR TITLE
Notes form the BoF @ RosCon 2013

### PR DESCRIPTION
**Pull request by stonier**
https://github.com/stonier/rosjava_core/blob/bof/docs/birds_of_a_feather-roscon-2013.rst

This doesn't necessarily have to be pulled in, though it might be nice to have it in docs for the record.

Use this pull request rather to generate discussion and I'll (Daniel) will update the document as we go.

### CODE REVIEW

**Comment by stonier** [comment]
**Actions**

A cursory list of actions we might look at immediately. Feel free to discuss, or add to the list or put your hand up if you'd like to work on one of these (I'll update this):
- Put CLA details in Damon's docs
- Pull request rosjava_jmdns into rosjava_core _[Daniel]_
  - Rosjava tutorials demo'ing polling and listening techniques into rosjava_core _[Daniel]_
  - Android demo application into android_core - master browser _[Daniel]_
- Pull request kazuto's non app manager patches into android_core
  - App manager code can go elsewhere -> ???
- Simple catkinizing tools for rosjava repositories _[Daniel]_
- Experiment with the android gradle plugin, report back.
- Setting up our own maven repository for rosjava dependencies
- Packaging rosjava repositories using bloom.

**Comment by stonier** [comment]
Q) Can we really not make use of our own android maven repository for jar dependencies like snakeyaml.jar?

I thought it would simply be a matter of having the android specific jar files there and making sure that repository is listed in the build.gradle file for the package.

**Comment by stonier** [comment]
Comment) After pondering it for a while I'm much more in favour of simple catkinizing of rosjava packages instead of a gradle super project underneath the multi-repo workspace - i.e. dependency tracking via package.xml and using a simple cmake macro (e.g. catkin_rosjava_repo_setup()) to add a custom target to the ALL build that calls on gradle. It has the advantages:
- Can build alongside catkinized msg packages in the source workspace
- Adds our packages to the ros wiki if we put it up for indexing
- Doesn't require any new tools to build with.

**Comment by stonier** [comment]
Q) On java package.names - should org.ros._pkg_name_ be strictly avoided?

Sorry if I'm raising an already discussed issue. This would seem a nice default for people who don't have their own unique internet domains since the package name in the ros world is generally required to be unique. It makes it easier configuring imports as well since you only have to remember the package name.

**Comment by damonkohler** [comment]
I wish I could reply inline... Maybe this would be better handled in Google Docs?

You can of course create your own maven repo and use it. You can list as many maven repos as you like in your build.gradle. I believe they're accessed in order, but you'll need to check the docs.

I'm not sure I understand your concerns/reasoning about catkinizing/gradle. We should discuss that tomorrow during the hangout.

Here's the documentation I wrote about Java package names: http://docs.rosjava.googlecode.com/hg/rosjava_core/html/best_practices.html#java-package-names

I think it is not hard for folks to come up with a replacement for org.ros._. The rest of the Java world manages :) One example would be using something like com.github.damonkohler._ or edu.ccny.\* or....

It's a useful signal when looking at stack traces. Seeing org.ros in the class name indicates that it's a core component.

**Comment by stonier** [comment]
We can certainly do a google doc next time if that's easier for you. I seem to bounce between that and repo or wiki docs depending on who I'm working with these days. Unfortunately, none has every feature you want!

Good to know we can draw jar dependencies for android from a maven repo, I must have misinterpreted a comment somewhere about that.

Package names - the github one is a good idea. Anyway, not a big issue, so I'm fine with that as well.

Catkinization - yes, let's discuss tonight.

**Comment by stonier** [comment]
I copied the contents of the rst file into a [google doc](https://docs.google.com/document/d/1GCDtKHZqhRCb9OWPXj2q30py5uSDssVE9Vqcnh3CD3g/edit?usp=sharing), and keeping track of progress on the [ros wiki](http://ros.org/wiki/sig/Rosjava) so I'll close this.

**Pull request closed without merging**
